name: Build Release Assets
on:
  push:
    branches: ['*']
  workflow_dispatch:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 1

jobs:
  build-macos-x86-64:
    runs-on: macOS-latest
    steps:
      - name: Cleanup Environment
        uses: Chia-Network/actions/clean-workspace@main

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Version Number
        id: version_number
        run: .github/actions/get-version.sh macos x86-64

      - name: Install Prerequisites
        run: brew install cmake

      - name: Build
        env:
          BB_ARTIFACT_NAME: ${{ steps.version_number.outputs.BB_ARTIFACT_NAME }}
          BB_VERSION: ${{steps.version_number.outputs.BB_VERSION}}
        run: .github/actions/build-asset-unix.sh

      - name: Upload Artifact macOS x86-64
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.version_number.outputs.BB_ARTIFACT_NAME }}
          path: ${{ github.workspace }}/bin/
          if-no-files-found: error
