name: Build Release Assets
on:
  push:
    branches: ['*']
  workflow_dispatch:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 1

jobs:
  build-macos-x86-64:
    name: tar - ${{ matrix.runs-on }} - ${{ matrix.n }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-11, macos-12, macos-latest]
        n: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]
    steps:
      - name: Cleanup Environment
        uses: Chia-Network/actions/clean-workspace@main

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Version Number
        id: version_number
        run: .github/actions/get-version.sh macos x86-64

      - name: Install Prerequisites
        run: brew install cmake

      - name: Build
        env:
          BB_ARTIFACT_NAME: ${{ steps.version_number.outputs.BB_ARTIFACT_NAME }}
          BB_VERSION: ${{steps.version_number.outputs.BB_VERSION}}
        run: .github/actions/build-asset-unix.sh

      - name: Upload Artifact macOS x86-64
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.runs-on }}-${{ matrix.n }}-${{ steps.version_number.outputs.BB_ARTIFACT_NAME }}
          path: ${{ github.workspace }}/bin/
          if-no-files-found: error
