name: Build Release Assets
on:
  push:
    branches: ['*']
  workflow_dispatch:

env:
  CI_BLADEBIT: 1  # Our own CI, that is, not being built as a dependency

jobs:
  build-harvester-linux-arm64:
    runs-on: [ARM64, Linux]
    container:
      image: quay.io/pypa/manylinux2014_aarch64
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache DNF packages
        uses: actions/cache@v3
        with:
          path: /var/cache/dnf
          key: ${{ runner.os }}-dnf-${{ hashFiles('**/your-build-file') }}
          restore-keys: |
            ${{ runner.os }}-dnf-

      - name: Get Version Number
        id: version_number
        shell: bash
        run: ./.github/actions/get-version.sh centos arm64

      - name: Install Prerequisites
        shell: bash
        run: |
          set -eo pipefail
          export module_platform_id=platform:el9
          export MODULE_PLATFORM_ID=platform:el9
          export PLATFORM_ID=platform:el9
          uname -a
          cat /etc/os-release
          yum install -y dnf
          dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          dnf install -y dnf-plugins-core
          dnf makecache
          dnf install -y kernel-headers.aarch64 kernel-devel.aarch64 tar bzip2 make automake gcc gcc-c++ pciutils elfutils-libelf-devel libglvnd-opengl libglvnd-glx libglvnd-devel acpid pkgconfig dkms
          dnf install -y cmake
          dnf group install -y "Development Tools"
          dnf install -y gmp-devel numactl-devel make git wget sed

      - name: Setup CUDA
        run: |
          set -eo pipefail
          module_platform_id=platform:el9
          export MODULE_PLATFORM_ID=platform:el9
          export PLATFORM_ID=platform:el9
          dnf config-manager --add-repo http://developer.download.nvidia.com/compute/cuda/repos/rhel9/$(uname -i)/cuda-rhel9.repo
          dnf config-manager --add-repo http://developer.download.nvidia.com/compute/cuda/repos/rhel9/sbsa/cuda-rhel9.repo
          dnf makecache
          #dnf install -y cuda.aarch64
          dnf install -y cuda-toolkit
          ls -la /usr/local/
          ls -la /usr/local/cuda*
          export PATH=/usr/local/cuda-12.1/bin${PATH:+:${PATH}}
          export LD_LIBRARY_PATH=/usr/local/cuda-12.1/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
      - name: Build Harvester
        shell: bash
        run: |
          export artifact_name="green_reaper-v${{ env.BB_VERSION }}-linux-ARM64"
          echo "harvester_artifact_name=${artifact_name}" >> "$GITHUB_ENV"
          # emits env.harvester_artifact_path
          bash .github/actions/build-harvester.sh --artifact "${artifact_name}"

      - name: Upload Harvester Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.harvester_artifact_name }}
          path: ${{ env.harvester_artifact_path }}
          if-no-files-found: error

  build-bladebit-cuda-linux-arm64:
    runs-on: [ARM64, Linux]
    container:
      image: chianetwork/ubuntu-20.04-builder:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Version Number
        id: version_number
        run: .github/actions/get-version.sh ubuntu arm64

      - name: Install Prerequisites
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update
          apt install -y build-essential git libgmp-dev libnuma-dev
      - name: Setup CUDA
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/cuda-ubuntu2004.pin
          mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
          wget https://developer.download.nvidia.com/compute/cuda/12.1.1/local_installers/cuda-repo-ubuntu2004-12-1-local_12.1.1-530.30.02-1_arm64.deb
          dpkg -i cuda-repo-ubuntu2004-12-1-local_12.1.1-530.30.02-1_arm64.deb
          cp /var/cuda-repo-ubuntu2004-12-1-local/cuda-*-keyring.gpg /usr/share/keyrings/
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get -y install cuda

      - name: Build
        run: .github/actions/build-asset-unix.sh --artifact ${{ env.BB_ARTIFACT_NAME }} --version ${{env.BB_VERSION}}

      - name: Upload Artifact Ubuntu ARM64
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BB_ARTIFACT_NAME }}
          path: ${{ github.workspace }}/bin/${{ env.BB_ARTIFACT_NAME }}
          if-no-files-found: error

      - name: Build Bladebit CUDA
        run: |
          .github/actions/build-asset-unix.sh --cuda --artifact ${{ env.BB_ARTIFACT_NAME_CUDA }} --version ${{ env.BB_VERSION }}
      - name: Upload Bladebit CUDA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BB_ARTIFACT_NAME_CUDA }}
          path: ${{ github.workspace }}/bin/${{ env.BB_ARTIFACT_NAME_CUDA }}
          if-no-files-found: error
